version: '3.7'

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address=":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=zpan
      - MINIO_ROOT_PASSWORD=zpanminio
      - MINIO_DOMAIN=minio.localhost

  zpan:
    image: saltbo/zpan:latest
    volumes:
      - zpcfg:/etc/zpan
      - zpdata:/srv # only for sqlite
    ports:
      - "8222:8222"
    depends_on:
      - minio

volumes:
  minio:
  zpcfg:
  zpdata:
